In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Dataset1.csv')

In [ ]:
df

,order_id,order_status,order_source,order_date,category,sku,quantity,sales,city
0,5447,Shipped,Whatsapp,04/01/2025,CK,Dng,1,1590,Karachi
1,14127,Shipped,Web,08/01/2025,CK,DIY,1,899,Karachi
2,14213,Shipped,Web,19/01/2025,CK,DIY,1,899,Karachi
3,14333,Shipped,Web,05/02/2025,CK,Simply9,1,990,Karachi
4,14397,Shipped,Web,16/02/2025,CK,Simply9,1,990,Karachi
...,...,...,...,...,...,...,...,...,...
792,5455,Shipped,Whatsapp,11/02/2025,HNS,101-15,2,8380,Lahore
793,14122,Shipped,Web,07/01/2025,WD,pta,5,8950,Rawalpindi
794,5542,Shipped,Whatsapp,27/01/2025,HNS,101-15,4,9500,Ghotki
795,5464,Shipped,Whatsapp,14/03/2025,HNS,101-12,8,11900,Lahore
796,5474,Shipped,Whatsapp,18/04/2025,HNS,101-18,4,13500,Ghotki

In [ ]:
df.shape

(797, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 797 entries, 0 to 796
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      797 non-null    int64
 1   order_status  797 non-null    object
 2   order_source  797 non-null    object
 3   order_date    797 non-null    object
 4   category      797 non-null    object
 5   sku           797 non-null    object
 6   quantity      797 non-null    int64
 7   sales         797 non-null    int64
 8   city          797 non-null    object
dtypes: int64(3), object(6)
memory usage: 56.2+ KB

In [ ]:
df.isnull().sum()

order_id        0
order_status    0
order_source    0
order_date      0
category        0
sku             0
quantity        0
sales           0
city            0
dtype: int64

In [ ]:
print(df.duplicated().sum())
print(df[df.duplicated(keep=False)])

12
     order_id order_status order_source  order_date category     sku  \
216      5466      Shipped     Whatsapp  21/03/2025      GfT  Eidi2p
217      5466      Shipped     Whatsapp  21/03/2025      GfT  Eidi2p
298     14678      Shipped          Web  24/04/2025      HNS  201-18
299     14678      Shipped          Web  24/04/2025      HNS  201-18
385     14321      Shipped          Web  01/02/2025      HNS  201-12
386     14321      Shipped          Web  01/02/2025      HNS  201-12
387     14321      Shipped          Web  01/02/2025      HNS  201-12
388     14321      Shipped          Web  01/02/2025      HNS  201-12
389     14321      Shipped          Web  01/02/2025      HNS  201-12
390     14321      Shipped          Web  01/02/2025      HNS  201-12
391     14321      Shipped          Web  01/02/2025      HNS  201-12
401     14717      Shipped          Web  04/05/2025      HNS  201-12
402     14717      Shipped          Web  04/05/2025      HNS  201-12
502     14258      Shipped          Web  24/01/2025       CK    OG16
503     14258      Shipped          Web  24/01/2025       CK    OG16
568     14296      Shipped          Web  29/01/2025      HNS  201-15
569     14296      Shipped          Web  29/01/2025      HNS  201-15
629     14558      Shipped          Web  02/04/2025      HNS  101-18
630     14558      Shipped          Web  02/04/2025      HNS  101-18

     quantity  sales        city
216         1   1190      Lahore
217         1   1190      Lahore
298         1   2190      Lahore
299         1   2190      Lahore
385         1   1190  Rawalpindi
386         1   1190  Rawalpindi
387         1   1190  Rawalpindi
388         1   1190  Rawalpindi
389         1   1190  Rawalpindi
390         1   1190  Rawalpindi
391         1   1190  Rawalpindi
401         1   1190   Islamabad
402         1   1190   Islamabad
502         1   1590   Hyderabad
503         1   1590   Hyderabad
568         1   1990   Wah Cantt
569         1   1990   Wah Cantt
629         1   3390      Multan
630         1   3390      Multan

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(785, 9)

In [ ]:
df.reset_index(drop=True, inplace=True)
df

,order_id,order_status,order_source,order_date,category,sku,quantity,sales,city
0,5447,Shipped,Whatsapp,04/01/2025,CK,Dng,1,1590,Karachi
1,14127,Shipped,Web,08/01/2025,CK,DIY,1,899,Karachi
2,14213,Shipped,Web,19/01/2025,CK,DIY,1,899,Karachi
3,14333,Shipped,Web,05/02/2025,CK,Simply9,1,990,Karachi
4,14397,Shipped,Web,16/02/2025,CK,Simply9,1,990,Karachi
...,...,...,...,...,...,...,...,...,...
780,5455,Shipped,Whatsapp,11/02/2025,HNS,101-15,2,8380,Lahore
781,14122,Shipped,Web,07/01/2025,WD,pta,5,8950,Rawalpindi
782,5542,Shipped,Whatsapp,27/01/2025,HNS,101-15,4,9500,Ghotki
783,5464,Shipped,Whatsapp,14/03/2025,HNS,101-12,8,11900,Lahore
784,5474,Shipped,Whatsapp,18/04/2025,HNS,101-18,4,13500,Ghotki

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
df.shape

(785, 9)

In [ ]:
df["order_date"].dtype

dtype('O')

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%d/%m/%Y')

In [ ]:
df['order_date'].head()

0   2025-01-04
1   2025-01-08
2   2025-01-19
3   2025-02-05
4   2025-02-16
Name: order_date, dtype: datetime64[ns]

In [ ]:
df["order_date"].dtype

dtype('<M8[ns]')

In [ ]:
df["order_date"].isnull().sum()

np.int64(0)

In [ ]:
for col in ["order_status", "order_source", "category", "city"]:
    print("\n", col)
    print(df[col].value_counts())

 order_status
order_status
Shipped      650
Cancelled    116
Hold          17
Pickup         1
Booked         1
Name: count, dtype: int64

 order_source
order_source
Web         737
Whatsapp     48
Name: count, dtype: int64

 category
category
HNS              391
CK               320
WD                36
GfT               33
Uncategorized      5
Name: count, dtype: int64

 city
city
Karachi          234
Lahore           169
Islamabad         68
Rawalpindi        38
Hyderabad         20
                ...
Larkana            1
kot addu           1
Pakpattan          1
Toba Tek Sing      1
Nowshera           1
Name: count, Length: 100, dtype: int64

In [ ]:
print(sorted(df['city'].unique()))

['ABDUL HAKIM', 'Abbottabad', 'Arifwala', 'BHAKKAR', 'Bahawalnagar', 'Bahawalpur', 'Batkhela', 'Batkhela Distt Malakand', 'Burewala', 'Chakwal', 'Charsadda', 'Chicha Watni', 'Chistian', 'DARGAI', 'DAULAT PUR', 'DIGRI', 'Depalpur', 'Dera Ghazi Khan', 'Dera Ismail Khan', 'Dera ala yar', 'Dharki', 'Faisalabad', 'GILGIT', 'Ghotki', 'Gujar Khan', 'Gujranwala', 'Gujrat', 'Hafizabad', 'Hasilpur', 'Hyderabad', 'Islamabad', 'Jampur', 'Jamshoro', 'Jhelum', 'KAMBER ALI KHAN', 'KHAIR PUR MEERU', 'Kabir Wala', 'Kamoki', 'Kandhkot', 'Karachi', 'Kark', 'Kasur', 'Khairpur', 'Khanewal', 'Khanpur', 'Kharian', 'Lahore', 'Lakki Marwat', 'Larkana', 'Liaqatpur', 'Lodhran', 'MIRAN SHAH', 'Mailsi', 'Mandi Bahauddin', 'Mansehra', 'Mardan', 'Mianwali', 'Mingora (swat)', 'Mirpur (a. K)', 'Mirpur Khas', 'Moro', 'Multan', 'Muzaffargarh', 'Nawab Shah', 'Nowshera', 'Nowshera virkan', 'Okara', 'Pakpattan', 'Pattoki', 'Peshawar', 'Pindi bhattian', 'Quetta', 'RENALAKHURD', 'Rahim yar khan', 'Raiwind', 'Rawalpindi', 'Retra', 'SANGHAR', 'Sadiqabad', 'Sahiwal', 'Sambrial', 'Sargodha', 'Sehwan', 'Sheikhupura', 'Shikarpur', 'Shorkot Cantt.', 'Sialkot', 'Sukkur', 'Swabi', 'Tando Adam', 'Tando ala yar', 'Taxila', 'Toba Tek Sing', 'Turbat', 'Vehari', 'Wah Cantt', 'Zaida', 'bannu', 'kot addu', 'کھڈیاں خاص']

In [ ]:
city_map = {
    # ALL CAPS entries where title() alone isn't quite right
    'RENALAKHURD': 'Renala Khurd',        # missing space, title() would give "Renalakhurd"

    # mixed-case entries title() won't touch (not fully upper or fully lower)
    'Mingora (swat)': 'Mingora (Swat)',
    'Mirpur (a. K)': 'Mirpur (AK)',
    'Nowshera virkan': 'Nowshera Virkan',
    'Pindi bhattian': 'Pindi Bhattian',
    'Rahim yar khan': 'Rahim Yar Khan',
    'Tando ala yar': 'Tando Allahyar',
    'Dera ala yar': 'Dera Allah Yar',

    # genuine misspellings
    'Toba Tek Sing': 'Toba Tek Singh',
    'Kark': 'Karak',

    # stray punctuation
    'Shorkot Cantt.': 'Shorkot Cantt',

    # duplicate/redundant variant of an existing city
    'Batkhela Distt Malakand': 'Batkhela',

    # non-Latin script entry, transliterated for consistency
    'کھڈیاں خاص': 'Khadian Khas',
}

df['city'] = df['city'].replace(city_map)

In [ ]:
df['city'] = df['city'].apply(
    lambda c: c.title() if (c.isupper() or c.islower()) else c
)

In [ ]:
print(sorted(df['city'].unique()))
print(df['city'].nunique())  # should drop from ~100 to a smaller, clean count

['Abbottabad', 'Abdul Hakim', 'Arifwala', 'Bahawalnagar', 'Bahawalpur', 'Bannu', 'Batkhela', 'Bhakkar', 'Burewala', 'Chakwal', 'Charsadda', 'Chicha Watni', 'Chistian', 'Dargai', 'Daulat Pur', 'Depalpur', 'Dera Allah Yar', 'Dera Ghazi Khan', 'Dera Ismail Khan', 'Dharki', 'Digri', 'Faisalabad', 'Ghotki', 'Gilgit', 'Gujar Khan', 'Gujranwala', 'Gujrat', 'Hafizabad', 'Hasilpur', 'Hyderabad', 'Islamabad', 'Jampur', 'Jamshoro', 'Jhelum', 'Kabir Wala', 'Kamber Ali Khan', 'Kamoki', 'Kandhkot', 'Karachi', 'Karak', 'Kasur', 'Khadian Khas', 'Khair Pur Meeru', 'Khairpur', 'Khanewal', 'Khanpur', 'Kharian', 'Kot Addu', 'Lahore', 'Lakki Marwat', 'Larkana', 'Liaqatpur', 'Lodhran', 'Mailsi', 'Mandi Bahauddin', 'Mansehra', 'Mardan', 'Mianwali', 'Mingora (Swat)', 'Miran Shah', 'Mirpur (AK)', 'Mirpur Khas', 'Moro', 'Multan', 'Muzaffargarh', 'Nawab Shah', 'Nowshera', 'Nowshera Virkan', 'Okara', 'Pakpattan', 'Pattoki', 'Peshawar', 'Pindi Bhattian', 'Quetta', 'Rahim Yar Khan', 'Raiwind', 'Rawalpindi', 'Renala Khurd', 'Retra', 'Sadiqabad', 'Sahiwal', 'Sambrial', 'Sanghar', 'Sargodha', 'Sehwan', 'Sheikhupura', 'Shikarpur', 'Shorkot Cantt', 'Sialkot', 'Sukkur', 'Swabi', 'Tando Adam', 'Tando Allahyar', 'Taxila', 'Toba Tek Singh', 'Turbat', 'Vehari', 'Wah Cantt', 'Zaida']
99

In [ ]:
print(df.isna().sum())
print((df['category'] == 'Uncategorized').sum())

order_id        0
order_status    0
order_source    0
order_date      0
category        0
sku             0
quantity        0
sales           0
city            0
dtype: int64
5

In [ ]:
print(df.shape)
print(df.dtypes)
print(df.isna().sum())
print(df.duplicated().sum())

(785, 9)
order_id                 int64
order_status            object
order_source            object
order_date      datetime64[ns]
category                object
sku                     object
quantity                 int64
sales                    int64
city                    object
dtype: object
order_id        0
order_status    0
order_source    0
order_date      0
category        0
sku             0
quantity        0
sales           0
city            0
dtype: int64
0

In [ ]:
df[['quantity', 'sales']].describe()

         quantity         sales
count  785.000000    785.000000
mean     1.059873   1931.326115
std      0.425863   1097.620687
min      1.000000    899.000000
25%      1.000000   1390.000000
50%      1.000000   1590.000000
75%      1.000000   2190.000000
max      8.000000  13500.000000

In [ ]:
print(df[df['quantity'] <= 0])
print(df[df['sales'] <= 0])

Empty DataFrame
Columns: [order_id, order_status, order_source, order_date, category, sku, quantity, sales, city]
Index: []
Empty DataFrame
Columns: [order_id, order_status, order_source, order_date, category, sku, quantity, sales, city]
Index: []

In [ ]:
Q1 = df[['quantity', 'sales']].quantile(0.25)
Q3 = df[['quantity', 'sales']].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower bounds:")
print(lower)

print("\nUpper bounds:")
print(upper)

Lower bounds:
quantity      1.0
sales       190.0
dtype: float64

Upper bounds:
quantity       1.0
sales       3390.0
dtype: float64

In [ ]:
outliers = df[
    (df['quantity'] < lower['quantity']) |
    (df['quantity'] > upper['quantity']) |
    (df['sales'] < lower['sales']) |
    (df['sales'] > upper['sales'])
]

print(outliers.shape)
print(outliers[['order_id', 'quantity', 'sales', 'sku', 'category']])

(43, 9)
     order_id  quantity  sales       sku       category
196     14824         1   3690    101-18            HNS
332     14135         1   3400    101-15            HNS
333     14164         1   3490      Neon             WD
334     14807         1   3690    101-18            HNS
335      7485         1   3690    101-18            HNS
336      5453         1   5200    101-15            HNS
337      5461         1   5600    201-18             CK
338      7483         1   5800    101-18            HNS
339     14821         1   6190    103-18            HNS
340      5475         1   9200    201-18            HNS
629      5454         1   3750    101-18            HNS
630     14518         1   4090   Eidi10p            GfT
631     14534         1   4090   Eidi10p            GfT
632    146311         1   4200    201-18            HNS
633     14813         1   6190    103-18            HNS
741     14159         1   3490      Neon  Uncategorized
742     14235         1   3490      Neon  Uncategorized
743     14370         1   3490      Neon  Uncategorized
760     14820         1   3690    101-18            HNS
761     14548         1   4490   Eidi10p            GfT
762     14278         5   1190   Minim12             CK
763     14549         2   1190    Eidi2p            GfT
764     14375         3   1490   Crclr15             CK
765     14300         2   1590       Dng             CK
766     14445         3   1590       Dng             CK
767     14363         2   1980    Minim9             CK
768     14268         2   2380    Hearts             WD
769     14436         2   2790  Simply15             CK
770     14258         2   2980   Swirl15             CK
771     14119         2   3180       Dng             CK
772     14725         2   3390    101-18            HNS
773      5445         3   3400    201-12            HNS
774     14394         3   3570  Triangle             WD
775      5463         2   3580    101-12            HNS
776     14604         4   3960   Simply9             CK
777     14131         4   4760        PD             WD
778      7480         2   6780    101-18            HNS
779     14434         2   6990      Neon  Uncategorized
780      5455         2   8380    101-15            HNS
781     14122         5   8950       pta             WD
782      5542         4   9500    101-15            HNS
783      5464         8  11900    101-12            HNS
784      5474         4  13500    101-18            HNS

In [ ]:
sku_category = df.groupby('sku')['category'].unique()

print(sku_category)

sku
001-12                      [HNS]
001-15                      [HNS]
001-9                       [HNS]
101-12                      [HNS]
101-15                      [HNS]
101-18                      [HNS]
103-18                      [HNS]
15x9                        [HNS]
18x11 matt                  [HNS]
201-12                      [HNS]
201-15                      [HNS]
201-18                  [HNS, CK]
BF                           [WD]
Birds                        [WD]
BoldS15                      [CK]
Cat15                        [CK]
Circles                      [WD]
Crclr12                      [CK]
Crclr15                      [CK]
DIY                          [CK]
Dng                          [CK]
Eidi10p                     [GfT]
Eidi2p                      [GfT]
Eidi4p                      [GfT]
Eidi5p                      [GfT]
Gear12                       [CK]
Gear15                       [CK]
Gear9                        [CK]
Geo12                        [CK]
Geo15                        [CK]
Hearts                       [WD]
Hexa                         [WD]
Minim12                      [CK]
Minim15                      [CK]
Minim9                       [CK]
Neon          [WD, Uncategorized]
OG16                         [CK]
Oval                         [WD]
PD                           [WD]
PacMan16                     [CK]
Rectangles                   [WD]
Silent12                     [CK]
Silent15                     [CK]
Silent18                     [CK]
Simply12                     [CK]
Simply15                     [CK]
Simply18                     [CK]
Simply9                      [CK]
Strips                       [WD]
SunCloud                     [WD]
SunClouds                    [WD]
SunFlower                    [WD]
Swirl15                      [CK]
Triangle                     [WD]
YY12                         [CK]
YY16                         [CK]
Zen12                        [CK]
Zen16                        [CK]
pta                          [WD]
Name: category, dtype: object

In [ ]:
print(
    df.groupby('sku')['category']
      .nunique()
      .sort_values(ascending=False)
)

sku
201-18        2
Neon          2
001-15        1
101-12        1
101-15        1
101-18        1
103-18        1
15x9          1
18x11 matt    1
201-12        1
001-12        1
201-15        1
BF            1
Birds         1
BoldS15       1
Cat15         1
Circles       1
Crclr12       1
Crclr15       1
DIY           1
Dng           1
Eidi10p       1
Eidi2p        1
Eidi4p        1
Eidi5p        1
Gear12        1
001-9         1
Gear15        1
Gear9         1
Geo15         1
Geo12         1
Hexa          1
Minim12       1
Minim15       1
Hearts        1
Minim9        1
OG16          1
Oval          1
PD            1
PacMan16      1
Rectangles    1
Silent12      1
Silent15      1
Silent18      1
Simply12      1
Simply15      1
Simply18      1
Simply9       1
Strips        1
SunCloud      1
SunClouds     1
SunFlower     1
Swirl15       1
Triangle      1
YY12          1
YY16          1
Zen12         1
Zen16         1
pta           1
Name: category, dtype: int64

In [ ]:
print(df[df['sku'].isin(['201-18', 'Neon'])][
    ['order_id', 'sku', 'category', 'quantity', 'sales']
].sort_values('sku'))

     order_id     sku       category  quantity  sales
146     14115  201-18            HNS         1   2190
563     14160  201-18            HNS         1   2190
565     14242  201-18            HNS         1   2190
567     14357  201-18            HNS         1   2190
572     14582  201-18            HNS         1   2190
575     14809  201-18            HNS         1   2490
576     14826  201-18            HNS         1   2490
580     14295  201-18            HNS         1   2590
581     14480  201-18            HNS         1   2590
583     14567  201-18            HNS         1   2590
587     14631  201-18            HNS         1   2590
591     14736  201-18            HNS         1   2590
597      5456  201-18            HNS         1   2590
632    146311  201-18            HNS         1   4200
711    142422  201-18            HNS         1   2190
713     14472  201-18            HNS         1   2190
715     14636  201-18             CK         1   2190
721     14573  201-18            HNS         1   2590
723     14672  201-18            HNS         1   2590
726     14789  201-18            HNS         1   2590
754     14688  201-18            HNS         1   2190
337      5461  201-18             CK         1   5600
340      5475  201-18            HNS         1   9200
184     14545  201-18            HNS         1   2690
156     14584  201-18            HNS         1   2190
158     14653  201-18            HNS         1   2190
164     14236  201-18            HNS         1   2590
169     14435  201-18            HNS         1   2590
173     14629  201-18            HNS         1   2590
182     14763  201-18            HNS         1   2590
183     14777  201-18            HNS         1   2590
316     14720  201-18            HNS         1   2590
294     14563  201-18            HNS         1   2190
151     14384  201-18            HNS         1   2190
295     14601  201-18            HNS         1   2190
297     14678  201-18            HNS         1   2190
298     14695  201-18            HNS         1   2190
303      7487  201-18            HNS         1   2490
305     14215  201-18            HNS         1   2590
308     14569  201-18            HNS         1   2590
309     14580  201-18            HNS         1   2590
310     14581  201-18            HNS         1   2590
313     14676  201-18            HNS         1   2590
315     14716  201-18            HNS         1   2590
296     14661  201-18            HNS         1   2190
743     14370    Neon  Uncategorized         1   3490
742     14235    Neon  Uncategorized         1   3490
333     14164    Neon             WD         1   3490
613      5460    Neon  Uncategorized         1   3300
741     14159    Neon  Uncategorized         1   3490
779     14434    Neon  Uncategorized         2   6990

In [ ]:
df.loc[df['sku'] == 'Neon', 'category'] = 'WD'

In [ ]:
print((df['category'] == 'Uncategorized').sum())

0

In [ ]:
df.loc[df['sku'] == 'Neon', 'category'] = 'WD'

In [ ]:
print(df['category'].value_counts())

category
HNS    391
CK     320
WD      41
GfT     33
Name: count, dtype: int64

In [ ]:
print(df[df['sku'] == 'Neon']['category'].unique())

['WD']

In [ ]:
df['order_id'].describe()

count    7.850000e+02
mean     1.670862e+04
std      5.114385e+04
min      5.444000e+03
25%      1.422900e+04
50%      1.441500e+04
75%      1.464100e+04
max      1.413666e+06
Name: order_id, dtype: float64

In [ ]:
print("Unique order IDs:", df['order_id'].nunique())
print("Total rows:", len(df))

Unique order IDs: 741
Total rows: 785

In [ ]:
df[df['order_id'].astype(str).str.len() > 5][
    ['order_id', 'order_date', 'sku', 'category', 'quantity', 'sales']
]

     order_id order_date     sku category  quantity  sales
139   1413666 2025-02-08  201-15      HNS         1   1990
143    146033 2025-04-08  201-15      HNS         1   1990
423    143599 2025-02-09  201-12      HNS         1   1390
477    141111 2025-01-05     Dng       CK         1   1590
632    146311 2025-04-11  201-18      HNS         1   4200
650    113544 2025-06-06  201-12      HNS         1   1190
711    142422 2025-01-22  201-18      HNS         1   2190

In [ ]:
print(df[df['order_id'].astype(str).str.len() < 4])

Empty DataFrame
Columns: [order_id, order_status, order_source, order_date, category, sku, quantity, sales, city]
Index: []

In [ ]:
df[df['order_id'].duplicated(keep=False)].sort_values('order_id')

,order_id,order_status,order_source,order_date,category,sku,quantity,sales,city
11,5462,Shipped,Whatsapp,2025-03-05,WD,Triangle,1,1090,Karachi
135,5462,Shipped,Whatsapp,2025-03-05,CK,Silent12,1,1790,Karachi
227,14096,Shipped,Web,2025-01-03,WD,SunFlower,1,1390,Lahore
278,14096,Shipped,Web,2025-01-03,WD,pta,1,1790,Lahore
119,14136,Shipped,Web,2025-01-11,HNS,201-12,1,1790,Karachi
...,...,...,...,...,...,...,...,...,...
666,14770,Cancelled,Web,2025-05-23,HNS,201-12,1,1390,Lahore
609,14781,Shipped,Web,2025-05-28,HNS,101-18,1,2890,Abbottabad
737,14781,Cancelled,Web,2025-05-28,HNS,001-15,1,2890,Abbottabad
575,14809,Shipped,Web,2025-06-06,HNS,201-18,1,2490,Faisalabad
555,14809,Shipped,Web,2025-06-06,HNS,201-15,1,1890,Faisalabad

In [ ]:
suspicious_ids = [1413666, 146033, 143599, 141111, 146311, 113544, 142422]

df[df['order_id'].isin(suspicious_ids)].sort_values('order_id')

,order_id,order_status,order_source,order_date,category,sku,quantity,sales,city
650,113544,Cancelled,Whatsapp,2025-06-06,HNS,201-12,1,1190,Karachi
477,141111,Shipped,Web,2025-01-05,CK,Dng,1,1590,Quetta
711,142422,Cancelled,Web,2025-01-22,HNS,201-18,1,2190,Rawalpindi
423,143599,Shipped,Web,2025-02-09,HNS,201-12,1,1390,Hyderabad
143,146033,Shipped,Web,2025-04-08,HNS,201-15,1,1990,Karachi
632,146311,Shipped,Web,2025-04-11,HNS,201-18,1,4200,Islamabad
139,1413666,Shipped,Whatsapp,2025-02-08,HNS,201-15,1,1990,Karachi

In [ ]:
df['sales_per_unit'] = df['sales'] / df['quantity']

df[['sku', 'quantity', 'sales', 'sales_per_unit']].sort_values('sku').head(30)

        sku  quantity  sales  sales_per_unit
161  001-12         1   2190          2190.0
159  001-12         1   2190          2190.0
163  001-12         1   2590          2590.0
595  001-12         1   2590          2590.0
596  001-12         1   2590          2590.0
573  001-12         1   2190          2190.0
566  001-12         1   2190          2190.0
170  001-12         1   2590          2590.0
174  001-12         1   2590          2590.0
160  001-12         1   2190          2190.0
612  001-12         1   3090          3090.0
317  001-12         1   2590          2590.0
330  001-15         1   3390          3390.0
733  001-15         1   2890          2890.0
611  001-15         1   2990          2990.0
737  001-15         1   2890          2890.0
628  001-15         1   3390          3390.0
193  001-15         1   3390          3390.0
676   001-9         1   1490          1490.0
710   001-9         1   2000          2000.0
543   001-9         1   1790          1790.0
536   001-9         1   1790          1790.0
121   001-9         1   1790          1790.0
678   001-9         1   1490          1490.0
79    001-9         1   1490          1490.0
281   001-9         1   1790          1790.0
78   101-12         1   1490          1490.0
537  101-12         1   1790          1790.0
77   101-12         1   1490          1490.0
80   101-12         1   1490          1490.0

In [ ]:
df[df['quantity'] > 1][
    ['sku', 'quantity', 'sales', 'sales_per_unit']
].sort_values('quantity', ascending=False)

          sku  quantity  sales  sales_per_unit
783    101-12         8  11900     1487.500000
781       pta         5   8950     1790.000000
762   Minim12         5   1190      238.000000
777        PD         4   4760     1190.000000
776   Simply9         4   3960      990.000000
784    101-18         4  13500     3375.000000
782    101-15         4   9500     2375.000000
766       Dng         3   1590      530.000000
764   Crclr15         3   1490      496.666667
774  Triangle         3   3570     1190.000000
773    201-12         3   3400     1133.333333
768    Hearts         2   2380     1190.000000
767    Minim9         2   1980      990.000000
765       Dng         2   1590      795.000000
763    Eidi2p         2   1190      595.000000
775    101-12         2   3580     1790.000000
770   Swirl15         2   2980     1490.000000
771       Dng         2   3180     1590.000000
772    101-18         2   3390     1695.000000
769  Simply15         2   2790     1395.000000
780    101-15         2   8380     4190.000000
778    101-18         2   6780     3390.000000
779      Neon         2   6990     3495.000000

In [ ]:
df.drop(columns=['sales_per_unit'], inplace=True)

In [ ]:
df.shape
df[['quantity', 'sales']].describe()

         quantity         sales
count  785.000000    785.000000
mean     1.059873   1931.326115
std      0.425863   1097.620687
min      1.000000    899.000000
25%      1.000000   1390.000000
50%      1.000000   1590.000000
75%      1.000000   2190.000000
max      8.000000  13500.000000

In [ ]:
df['order_status'].value_counts()

order_status
Shipped      650
Cancelled    116
Hold          17
Pickup         1
Booked         1
Name: count, dtype: int64

In [ ]:
df['order_status'].unique()

array(['Shipped', 'Cancelled', 'Hold', 'Pickup', 'Booked'], dtype=object)

In [ ]:
df['order_source'].value_counts()

order_source
Web         737
Whatsapp     48
Name: count, dtype: int64

In [ ]:
df['order_source'].unique()

array(['Whatsapp', 'Web'], dtype=object)

In [ ]:
df['city'].value_counts()

city
Karachi           234
Lahore            169
Islamabad          68
Rawalpindi         38
Hyderabad          20
                 ...
Khadian Khas        1
Kot Addu            1
Pakpattan           1
Toba Tek Singh      1
Nowshera            1
Name: count, Length: 99, dtype: int64

In [ ]:
df['category'].value_counts()

category
HNS    391
CK     320
WD      41
GfT     33
Name: count, dtype: int64

In [ ]:
print("Unique SKUs:", df['sku'].nunique())
print(df['sku'].unique())

Unique SKUs: 59
['Dng' 'DIY' 'Simply9' 'Eidi2p' 'Geo12' 'Simply12' 'Triangle' 'Minim12'
 'Gear12' '201-12' 'Swirl15' 'Circles' 'Crclr12' 'Zen12' 'YY12' 'Geo15'
 'BoldS15' 'pta' 'Simply15' '101-12' 'Minim15' 'Gear15' 'Crclr15' 'PD'
 '001-9' 'Zen16' 'Silent12' 'Rectangles' 'YY16' '201-15' '201-18'
 'Silent18' '101-15' 'Eidi5p' '001-12' '101-18' '103-18' '001-15' 'Minim9'
 'Oval' 'SunFlower' 'SunClouds' 'Cat15' 'PacMan16' 'Silent15' 'Eidi4p'
 'Neon' 'BF' 'Gear9' 'Birds' 'Strips' 'SunCloud' 'OG16' 'Hexa'
 '18x11 matt' 'Eidi10p' 'Simply18' '15x9' 'Hearts']

In [ ]:
df[df['quantity'] > 1][['sku', 'quantity', 'sales']].sort_values('sku')

          sku  quantity  sales
775    101-12         2   3580
783    101-12         8  11900
782    101-15         4   9500
780    101-15         2   8380
784    101-18         4  13500
778    101-18         2   6780
772    101-18         2   3390
773    201-12         3   3400
764   Crclr15         3   1490
771       Dng         2   3180
766       Dng         3   1590
765       Dng         2   1590
763    Eidi2p         2   1190
768    Hearts         2   2380
762   Minim12         5   1190
767    Minim9         2   1980
779      Neon         2   6990
777        PD         4   4760
769  Simply15         2   2790
776   Simply9         4   3960
770   Swirl15         2   2980
774  Triangle         3   3570
781       pta         5   8950

In [ ]:
# get the "typical" single-unit price for each SKU from quantity=1 rows
unit_price = df[df['quantity'] == 1].groupby('sku')['sales'].median()

# for quantity>1 rows, compare actual sales to what it *should* be
check = df[df['quantity'] > 1].copy()
check['expected_price'] = check['sku'].map(unit_price)
check['expected_sales'] = check['expected_price'] * check['quantity']
check['mismatch'] = check['sales'] != check['expected_sales']

print(check[check['mismatch']][['sku','quantity','sales','expected_sales']])

          sku  quantity  sales  expected_sales
762   Minim12         5   1190          5950.0
763    Eidi2p         2   1190          1998.0
764   Crclr15         3   1490          4470.0
765       Dng         2   1590          3180.0
766       Dng         3   1590          4770.0
768    Hearts         2   2380             NaN
769  Simply15         2   2790          2780.0
770   Swirl15         2   2980          2680.0
772    101-18         2   3390          6780.0
773    201-12         3   3400          4020.0
774  Triangle         3   3570          3270.0
775    101-12         2   3580          3280.0
779      Neon         2   6990          6980.0
780    101-15         2   8380          5180.0
781       pta         5   8950          7950.0
782    101-15         4   9500         10360.0
783    101-12         8  11900         13120.0
784    101-18         4  13500         13560.0

In [ ]:
check['sales_flag'] = np.where(
    (check['sales'] == check['expected_price']) &
    (check['quantity'] > 1),
    'quantity not applied - verify',
    'OK'
)

In [ ]:
check[check['sales_flag'] == 'quantity not applied - verify']

,order_id,order_status,order_source,order_date,category,sku,quantity,sales,city,expected_price,expected_sales,mismatch,sales_flag
762,14278,Cancelled,Web,2025-01-26,CK,Minim12,5,1190,Digri,1190.0,5950.0,True,quantity not applied - verify
764,14375,Cancelled,Web,2025-02-13,CK,Crclr15,3,1490,Islamabad,1490.0,4470.0,True,quantity not applied - verify
765,14300,Cancelled,Web,2025-01-29,CK,Dng,2,1590,Sheikhupura,1590.0,3180.0,True,quantity not applied - verify
766,14445,Cancelled,Web,2025-02-26,CK,Dng,3,1590,Karachi,1590.0,4770.0,True,quantity not applied - verify
772,14725,Cancelled,Web,2025-05-08,HNS,101-18,2,3390,Lahore,3390.0,6780.0,True,quantity not applied - verify

In [ ]:
df['sales_flag'] = 'OK'

df.loc[check.index, 'sales_flag'] = check['sales_flag']

In [ ]:
df['sales_flag'].value_counts()

sales_flag
OK                               780
quantity not applied - verify      5
Name: count, dtype: int64

In [ ]:
df['sku'].str.strip().ne(df['sku']).sum()

np.int64(0)

In [ ]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nUnique values:")
print(df.nunique())

Shape: (785, 10)

Missing values:
order_id        0
order_status    0
order_source    0
order_date      0
category        0
sku             0
quantity        0
sales           0
city            0
sales_flag      0
dtype: int64

Duplicate rows: 0

Data types:
order_id                 int64
order_status            object
order_source            object
order_date      datetime64[ns]
category                object
sku                     object
quantity                 int64
sales                    int64
city                    object
sales_flag              object
dtype: object

Unique values:
order_id        741
order_status      5
order_source      2
order_date      139
category          4
sku              59
quantity          6
sales            64
city             99
sales_flag        2
dtype: int64

In [ ]:
# Remove temporary checking columns if they exist
temp_cols = ['expected_price', 'expected_sales', 'mismatch', 'unit_ratio']

df.drop(columns=[col for col in temp_cols if col in df.columns], inplace=True)

# Final check
print("Shape:", df.shape)
print("Missing values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print(df['sales_flag'].value_counts())

Shape: (785, 10)
Missing values: 0
Duplicate rows: 0
sales_flag
OK                               780
quantity not applied - verify      5
Name: count, dtype: int64

In [ ]:
df.to_csv('/content/Cleaned_Dataset.csv', index=False)

In [ ]:
pd.read_csv('/content/Cleaned_Dataset.csv').shape

(785, 10)

In [ ]:
from google.colab import files

files.download('/content/Cleaned_Dataset.csv')